# Generated by Django 5.0.6 on 2024-06-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_generalsetting_created_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254, verbose_name='Name ')),
                ('description', models.CharField(blank=True, default='', max_length=254, verbose_name='Description ')),
                ('file', models.FileField(blank=True, default='', upload_to='images/', verbose_name='Image ')),
            ],
        ),
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'ordering': ('name',), 'verbose_name': 'General Settings'},
        ),
    ]
