# Generated by Django 5.0.6 on 2024-06-03 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_imagesettings_imagesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_data', models.DateTimeField(auto_now=True, verbose_name='Updated Date ')),
                ('created_data', models.DateTimeField(auto_now_add=True, verbose_name='Created Date ')),
                ('order', models.IntegerField(default=0, verbose_name='Order ')),
                ('name', models.CharField(blank=True, default='', help_text='This is val. of the Setting', max_length=254, verbose_name='Name ')),
                ('percentage', models.IntegerField(blank=True, default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
