# Generated by Django 5.0.6 on 2024-06-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_skill_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_data', models.DateTimeField(auto_now=True, verbose_name='Updated Date ')),
                ('created_data', models.DateTimeField(auto_now_add=True, verbose_name='Created Date ')),
                ('company_name', models.CharField(blank=True, default='', max_length=254, verbose_name='Company Name ')),
                ('job_tittle', models.CharField(blank=True, default='', max_length=254, verbose_name='Job Tittle ')),
                ('job_location', models.CharField(blank=True, default='', max_length=254, verbose_name='Job Location ')),
                ('start_date', models.DateTimeField(verbose_name='Start Date ')),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='End Date ')),
            ],
            options={
                'verbose_name': 'Experience Settings',
                'ordering': ('start_date',),
            },
        ),
    ]
