# Generated by Django 5.0.6 on 2024-06-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Start Date '),
        ),
    ]
