# Generated by Django 5.0.6 on 2024-06-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_data', models.DateTimeField(auto_now=True, verbose_name='Updated Date ')),
                ('created_data', models.DateTimeField(auto_now_add=True, verbose_name='Created Date ')),
                ('order', models.IntegerField(default=0, verbose_name='Order ')),
                ('link', models.CharField(blank=True, default='', max_length=254, verbose_name='Link ')),
                ('icon', models.CharField(blank=True, default='', max_length=254, verbose_name='Icon ')),
            ],
            options={
                'verbose_name': 'Social Media Setting',
                'verbose_name_plural': 'Social Media Settings',
                'ordering': ('order',),
            },
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('start_date',), 'verbose_name': 'Education Setting', 'verbose_name_plural': 'Education Settings'},
        ),
        migrations.AlterField(
            model_name='education',
            name='education_location',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Education Location '),
        ),
        migrations.AlterField(
            model_name='education',
            name='education_lvl',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Education Level '),
        ),
        migrations.AlterField(
            model_name='education',
            name='education_name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Education Name '),
        ),
    ]
