# Generated by Django 5.0.6 on 2024-06-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_socialmedia_alter_education_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_data', models.DateTimeField(auto_now=True, verbose_name='Updated Date ')),
                ('created_data', models.DateTimeField(auto_now_add=True, verbose_name='Created Date ')),
                ('order', models.IntegerField(default=0, verbose_name='Order ')),
                ('name', models.CharField(blank=True, default='', max_length=254, verbose_name='Name ')),
                ('button_text', models.CharField(blank=True, default='', max_length=254, verbose_name='Button Text ')),
                ('file', models.FileField(blank=True, default='', upload_to='documents/', verbose_name='Image ')),
            ],
            options={
                'verbose_name': 'Document Settings',
                'ordering': ('order',),
            },
        ),
    ]
